import{S as s}from"./assets/vendor-CgTBfC_f.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const t of o)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function n(o){const t={};return o.integrity&&(t.integrity=o.integrity),o.referrerPolicy&&(t.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?t.credentials="include":o.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(o){if(o.ep)return;o.ep=!0;const t=n(o);fetch(o.href,t)}})();const l=[{preview:"https://cdn.pixabay.com/photo/2019/05/14/16/43/rchids-4202820__480.jpg",original:"https://cdn.pixabay.com/photo/2019/05/14/16/43/rchids-4202820_1280.jpg",description:"Hokkaido Flower"},{preview:"https://cdn.pixabay.com/photo/2019/05/14/22/05/container-4203677__340.jpg",original:"https://cdn.pixabay.com/photo/2019/05/14/22/05/container-4203677_1280.jpg",description:"Container Haulage Freight"},{preview:"https://cdn.pixabay.com/photo/2019/05/16/09/47/beach-4206785__340.jpg",original:"https://cdn.pixabay.com/photo/2019/05/16/09/47/beach-4206785_1280.jpg",description:"Aerial Beach View"},{preview:"https://cdn.pixabay.com/photo/2016/11/18/16/19/flowers-1835619__340.jpg",original:"https://cdn.pixabay.com/photo/2016/11/18/16/19/flowers-1835619_1280.jpg",description:"Flower Blooms"},{preview:"https://cdn.pixabay.com/photo/2018/09/13/10/36/mountains-3674334__340.jpg",original:"https://cdn.pixabay.com/photo/2018/09/13/10/36/mountains-3674334_1280.jpg",description:"Alpine Mountains"},{preview:"https://cdn.pixabay.com/photo/2019/05/16/23/04/landscape-4208571__340.jpg",original:"https://cdn.pixabay.com/photo/2019/05/16/23/04/landscape-4208571_1280.jpg",description:"Mountain Lake Sailing"},{preview:"https://cdn.pixabay.com/photo/2019/05/17/09/27/the-alps-4209272__340.jpg",original:"https://cdn.pixabay.com/photo/2019/05/17/09/27/the-alps-4209272_1280.jpg",description:"Alpine Spring Meadows"},{preview:"https://cdn.pixabay.com/photo/2019/05/16/21/10/landscape-4208255__340.jpg",original:"https://cdn.pixabay.com/photo/2019/05/16/21/10/landscape-4208255_1280.jpg",description:"Nature Landscape"},{preview:"https://cdn.pixabay.com/photo/2019/05/17/04/35/lighthouse-4208843__340.jpg",original:"https://cdn.pixabay.com/photo/2019/05/17/04/35/lighthouse-4208843_1280.jpg",description:"Lighthouse Coast Sea"}];try{const e=document.querySelector(".gallery");if(!e)throw new Error("Gallery container not found");const r=p(l);e.innerHTML=r;const n=new s(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250})}catch(e){console.error("An error occurred:",e)}function p(e){try{return e.map(({small:r,large:n,description:i})=>{if(!r||!n||!i)throw new Error("Invalid image data");return`
                <li class="gallery-item">
                    <a class="gallery-link" href="${n}">
                        <img 
                            class="gallery-image" 
                            src="${r}" 
                            alt="${i}" 
                        />
                    </a>
                </li>
            `}).join("")}catch(r){return console.error("An error occurred while creating gallery markup:",r),""}}const a={email:"",message:""};function d(e){try{localStorage.setItem("feedback-form-state",JSON.stringify(e))}catch(r){console.error("Error saving to localStorage",r)}}function m(){try{const e=localStorage.getItem("feedback-form-state");return e?JSON.parse(e):null}catch(e){return console.error("Error loading from localStorage",e),null}}function g(e){try{document.querySelector('input[name="email"]').value=e.email,document.querySelector('textarea[name="message"]').value=e.message}catch(r){console.error("Error updating form fields",r)}}function u(e){try{e.reset()}catch(r){console.error("Error resetting form",r)}}document.querySelector(".feedback-form").addEventListener("input",e=>{try{const{name:r,value:n}=e.target;a[r]=n,d(a)}catch(r){console.error("Error handling input event",r)}});document.addEventListener("DOMContentLoaded",()=>{try{const e=m();e&&(Object.assign(a,e),g(a))}catch(e){console.error("Error on DOMContentLoaded",e)}});document.querySelector(".feedback-form").addEventListener("submit",e=>{e.preventDefault();try{if(!a.email||!a.message){alert("Fill please all fields");return}console.log(a),localStorage.removeItem("feedback-form-state"),a.email="",a.message="",u(e.target)}catch(r){console.error("Error handling form submission",r)}});
//# sourceMappingURL=index.js.map
